# ShowDateAndTimeBegin
# DssableTelemetry
# DssableWiFiSense
# DssableSmartScreen
# DssableWebSearch
# DssableAppSuggestions
# DssableActivityHistory
# DssableBackgroundApps
# DssableSensors
# DssableLocation
# DssableMapUpdates
# DssableFeedback
# DssableTailoredExperiences
# DssableAdvertisingID
# DssableWebLangList
# DssableCortana
# DssableCamera
# DssableMicrophone
# DssableErrorReporting
# SetP2PUpdateLocal
# Dssable DsagTrack
# DssableWAPPush
# EnableClearRecentFiles
# DssableRecentFiles
# SetUACLow
# DssableAdminShares
# DssableDefenderCloud
# EnableCtrldFolderAccess
# EnableCIMemoryIntegrity
# DssableDefenderAppGuard
# HideAccountProtectionWarn
# DssableDownloadBlocking
# EnableF8BootMenu
# SetCurrentNetworkPublic
# SetUnknownNetworksPublic
# DssableNetDevicesAutoInst
# DssableSMBServer
# DssableNetBIOS
# EnableLLMNR
# EnableLLDP
# DssableMSNetClient
# DssableQoS
# DssableConnectionSharing
# DssableRemoteAssistance
# EnableRemoteDesktop
# EnableUpdateMSProducts
# DssableUpdateAutoDownload
# DssableMaintenanceWakeUp
# DssableSharedExperiences
# DssableClipboard# History
# DssableAutoplay
# DssableAutorun
# DssableStorageSense
# DssableDefragmentation
# DssableSuperfetch
# DssableIndexing
# DssableSwapFile
# DssableRecycleBin
# EnableNTFSLastAccess
# Dssable# Hibernation
# DssableSleepButton
# DssableSleepTimeout
# SetupScreenSaver
# DssableFastStartup
# ChangeBackgroundColor
# DssableActionCenter
# # HideNetworkFromLockScreen
# DssableAccessibilityKeys
# ShowTaskManagerDetails
# EnableFileDeleteConfirm
# HideTaskbarSearch
# HideTaskView
# ShowSmallTaskbarIcons
# SetTaskbarCombineNever
# HideTaskbarPeopleIcon
# ShowTrayIcons
# DssableSearchAppInStore
# DssableNewAppPrompt
# HideRecentlyAddedApps
# HideMostUsedApps
# SetControlPanelSmallIcons
# DssableShortcutInName
# HideShortcutArrow
# SetVisualFXPerformance
# DssableTitleBarColor
# EnableDarkTheme
# DssableF1HelpKey
# ShowExplorerTitleFullPath
# ShowKnownExtensions
# ShowHiddenFiles
# EnableNavPaneExpand
# ShowNavPaneAllFolders
# DssableFldrSeparateProcess
# DssableRestoreFldrWindows
# ShowEncCompFilesColor
# DssableSharingWizard
# HideSyncNotifications
# HideRecentShortcuts
# SetExplorerThisPC
# HideQuickAccess
# HideRecycleBinFromDesktop
# ShowThisPCOnDesktop
# HideUserFolderFromDesktop
# ShowControlPanelOnDesktop
# HideNetworkFromDesktop
# ShowBuildNumberFromDesktop
# MoveUserFolders
# HideDesktopFromThisPC
# HideDesktopFromExplorer
# HideDocumentsFromThisPC
# HideDownloadsFromThisPC
# HideDownloadsFromExplorer
# HideMusicFromThisPC
# HideMusicFromExplorer
# HidePicturesFromThisPC
# HidePicturesFromExplorer
# HideVideosFromThisPC
# HideVideosFromExplorer
# Hide3DObjectsFromThisPC
# Hide3DObjectsFromExplorer
# HideIncludeInLibraryMenu
# HideGiveAccessToMenu
# HideShareMenu
# DssableThumbnails
# DssableThumbnailCache
# DssableThumbsDBOnNetwork
# DssableOneDrive
# UninstallMsftBloat
# UninstallThirdPartyBloat
# UninstallWindowsStore
# DssableXboxFeatures
# DssableProvisionedPackage
# DssableFullscreenOptims
# DssableAdobeFlash
# DssableEdgePreload
# DssableEdgeShortcutCreation
# DssableIEFirstRun
# DssableMe# DsaSharing
InstallXPSPrinter
UninstallMediaPlayer
# UninstallInternetExplorer
# UninstallWorkFolders
# UninstallPowerShellV2
# UninstallLinuxSubsystem
# InstallHyperV
# UninstallBrowserInternetExplorer
# UninstallHelloFace
# UninstallLanguageHandwriting
# UninstallLanguageOCR
# UninstallLanguageSpeech
# UninstallLanguageTextToSpeech
# UninstallMathRecognizer
# UninstallOneCoreUAPOneSync
# InstallSSHClient
# InstallSSHServer
# InstallNET23
# UninstallQuickAssist
# UninstallPDFPrinter
# UninstallXPSPrinter
# RemoveFaxPrinter
# UninstallFaxAndScan
# UnpinStartMenuTiles
# UninstallOneDrive
# InstallChoco
# Cinst
# ShowDateAndTimeEnd
# WaitForKey
# Restart